version: '2'

services:
  backend0:
    build: .
    ports:
     - "8080:8080"
  backend1:
    build: .
    ports:
     - "8081:8080"
  backend2:
    build: .
    ports:
     - "8082:8080"
  backend3:
    build: .
    ports:
     - "8083:8080"
  frontend:
    image: nginx:alpine
    ports:
     - "85:80"
    links:
     - backend0
     - backend1
     - backend2
     - backend3
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
